# Generated by Django 5.0.1 on 2024-08-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=500)),
                ('numero_factura', models.CharField(max_length=255)),
                ('habitacion', models.CharField(max_length=255)),
                ('habitacion_numero', models.IntegerField()),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('alojamiento_dias', models.IntegerField()),
                ('desayuno_dias', models.IntegerField()),
                ('alojamiento_precio', models.FloatField()),
                ('desayuno_precio', models.FloatField()),
                ('base_imponible', models.FloatField()),
                ('porcentaje_iva', models.IntegerField()),
                ('importe_iva', models.FloatField()),
                ('total_factura', models.FloatField()),
            ],
        ),
    ]
