# Generated by Django 5.0.1 on 2024-08-19 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2024, 8, 19)),
        ),
    ]
