# Generated by Django 5.0.1 on 2024-08-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='importe',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('alojamiento', 'Alojamiento'), ('desayuno', 'Desayuno')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
