# Generated by Django 5.0.1 on 2024-07-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0002_articulo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='habitacion',
            field=models.CharField(max_length=255),
        ),
    ]
