# Generated by Django 5.0.1 on 2024-07-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0003_alter_factura_habitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='importe',
        ),
    ]
