# Generated by Django 5.0.1 on 2024-09-19 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0003_cliente_alter_factura_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_cuenta',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2024, 9, 19)),
        ),
    ]
