# Generated by Django 5.0.1 on 2024-09-24 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0004_factura_numero_cuenta_alter_factura_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2024, 9, 24)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
