# Generated by Django 5.0.1 on 2024-07-17 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0004_remove_factura_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoronaCastilla.articulo'),
        ),
    ]
