# Generated by Django 5.0.1 on 2024-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0005_alter_factura_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='alojamiento_precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='desayuno_precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
