# Generated by Django 5.0.1 on 2024-10-02 08:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0005_alter_factura_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='alojamiento_dias',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='alojamiento_precio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='habitacion_numero',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2024, 10, 2)),
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_habitacion', models.CharField(choices=[('individual', 'Habitación individual'), ('doble', 'Habitación doble'), ('triple', 'Habitación triple'), ('cuadruple', 'Habitación cuadruple')], max_length=255)),
                ('numero_habitacion', models.IntegerField()),
                ('alojamiento_dias', models.IntegerField()),
                ('alojamiento_precio', models.FloatField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='CoronaCastilla.factura')),
            ],
        ),
    ]
