# Generated by Django 5.0.1 on 2024-07-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0006_alter_factura_alojamiento_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='alojamiento_precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='desayuno_precio',
            field=models.FloatField(),
        ),
    ]
