# Generated by Django 5.0.1 on 2024-10-09 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0006_remove_factura_alojamiento_dias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='desayuno_dias',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='alojamiento_dias',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2024, 10, 9)),
        ),
    ]
