# Generated by Django 5.1.2 on 2024-12-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoronaCastilla', '0009_habitacion_alojamiento_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='desayuno2_cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='desayuno2_precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='desayuno_cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='desayuno_precio',
            field=models.FloatField(),
        ),
    ]
